#!/usr/bin/python
from blog import say, Archive

""" Move the most recent blog entry in
    the archive to the index page of
    the blog.
"""


arch = Archive()
arch.publish()
post = arch.get()

say('Front page changed to post "' + post['title'] + '"!')

