#!/usr/bin/python

import argparse
# Custom shite.
from blog import say, Archive

""" Create a new blog post using the template in ./template.html.
    The template is written with the given post title, and the
    current date.
"""

parser = argparse.ArgumentParser(description='Create a new blog post and add it to the archive.')
parser.add_argument('title', help='blog post title')
parser.add_argument('--file', default=None, help='name to use for the file')
args = parser.parse_args()

arch = Archive()
path = arch.new(args.title, args.file)

say('Created post at ' + path)
say('Once you are done editing, use ./publish.')


